runtime! archlinux.vim

let mapleader = " "

set relativenumber

set formatoptions-=cro
set splitbelow splitright
set undofile

set tabstop=4
set shiftwidth=4
set expandtab

map <S-l> :bnext<CR>
map <S-h> :bprev<CR>

map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

nnoremap <leader>y "*y
nnoremap <leader>p "*p
nnoremap <leader>d "*d

" remove trailing whitespace
set wrap
set linebreak
" note trailing space at end of next line
set showbreak=>\ \ \
autocmd BufWritePre * :%s/\s\+$//e
